# Generated by Django 3.2.7 on 2021-11-11 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0016_auto_20211110_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='randomiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='surveybuilder.randomiser'),
        ),
        migrations.AlterField(
            model_name='randomiser',
            name='subset',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='randomiser',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveybuilder.survey'),
        ),
    ]
