# Generated by Django 3.2.7 on 2021-11-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0016_auto_20211112_0943'),
        ('surveybuilder', '0018_alter_block_randomiser'),
    ]

    operations = [
    ]
